### ISSUE TITLE
WHY are you doing this to me

### ISSUE THREAD

**Issue by catmanbobina** [cole-wilson/cole-wilson.github.io#2]
**Describe the bug**
File not found
**To Reproduce**
1. Go to ['https://cole-wilson.github.io'](https://cole-wilson.github.io)
2. Click on 'Donate'

**Expected behavior**
Donate page.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ChromeOS
 - Browser Chrome

**Comment by cole-wilson** [comment]
you are wrong

**Comment by catmanbobina** [comment]
No you

**Comment by catmanbobina** [comment]
no tyou

**Comment by catmanbobina** [comment]
no |]
ou

**Comment by catmanbobina** [comment]
no you

**Comment by catmanbobina** [comment]
![image](https://user-images.githubusercontent.com/58565643/70346621-9450f400-1813-11ea-839b-c266a2217146.png)
